// Generated by Selenium IDE

import org.junit.Test;

import org.junit.Before;

import org.junit.After;

import static org.junit.Assert.*;

import static org.hamcrest.CoreMatchers.is;

import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;

import org.openqa.selenium.WebDriver;

import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.remote.RemoteWebDriver;

import org.openqa.selenium.remote.DesiredCapabilities;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.WebElement;

import org.openqa.selenium.interactions.Actions;

import org.openqa.selenium.support.ui.ExpectedConditions;

import org.openqa.selenium.support.ui.WebDriverWait;

import org.openqa.selenium.JavascriptExecutor;

import org.openqa.selenium.Alert;

import org.openqa.selenium.Keys;

import java.util.*;

import java.net.MalformedURLException;

import java.net.URL;


public class Prueba3Test {

  private WebDriver driver;

  private Map<String, Object> vars;

  JavascriptExecutor js;
 

 @Before

  public void setUp() {

    driver = new ChromeDriver();

    js = (JavascriptExecutor) driver;

    vars = new HashMap<String, Object>();

  }
 

 @After
 
 public void tearDown() {

    driver.quit();

  }


  @Test

  public void prueba3() {

    // Test name: Prueba 3
 

   // Step # | name | target | value
    // 1 | open | /login | 

    driver.get("http://travel.agileway.net/login");


    // 2 | setWindowSize | 1050x840 | 

    driver.manage().window().setSize(new Dimension(1050, 840));
 

   // 3 | click | id=username | 
 
   driver.findElement(By.id("username")).click();


    // 4 | type | id=username | agileway
 
   driver.findElement(By.id("username")).sendKeys("agileway");
 

   // 5 | click | id=password | 
 
   driver.findElement(By.id("password")).click();


    // 6 | type | id=password | testwise
 
   driver.findElement(By.id("password")).sendKeys("testwise");


    // 7 | click | name=commit | 
 
   driver.findElement(By.name("commit")).click();


    // 8 | click | name=fromPort | 
 
   driver.findElement(By.name("fromPort")).click();

    // 9 | select | name=fromPort | label=San Francisco
 
   {
 
     WebElement dropdown = driver.findElement(By.name("fromPort"));
 
     dropdown.findElement(By.xpath("//option[. = 'San Francisco']")).click();


    }
 

   // 10 | click | name=toPort | 
 
   driver.findElement(By.name("toPort")).click();
 

   // 11 | select | name=toPort | label=New York
 
   {
  
    WebElement dropdown = driver.findElement(By.name("toPort"));

      dropdown.findElement(By.xpath("//option[. = 'New York']")).click();


    }
  

  // 12 | click | id=departDay | 
 
   driver.findElement(By.id("departDay")).click();


    // 13 | select | id=departDay | label=05
 
   {
 
     WebElement dropdown = driver.findElement(By.id("departDay"));
 
     dropdown.findElement(By.xpath("//option[. = '05']")).click();


    }


    // 14 | click | id=departMonth | 
  
  driver.findElement(By.id("departMonth")).click();


    // 15 | select | id=departMonth | label=May 2023
 
   {
  
    WebElement dropdown = driver.findElement(By.id("departMonth"));
  
    dropdown.findElement(By.xpath("//option[. = 'May 2023']")).click();

    }
 

   // 16 | click | id=returnDay | 
 
   driver.findElement(By.id("returnDay")).click();


    // 17 | select | id=returnDay | label=07
   
 {
  
    WebElement dropdown = driver.findElement(By.id("returnDay"));
 
     dropdown.findElement(By.xpath("//option[. = '07']")).click();


    }
 
   // 18 | click | id=returnMonth | 
  
  driver.findElement(By.id("returnMonth")).click();
 

   // 19 | select | id=returnMonth | label=July 2023
  
  {
  
    WebElement dropdown = driver.findElement(By.id("returnMonth"));

      dropdown.findElement(By.xpath("//option[. = 'July 2023']")).click();

    }
  

  // 20 | click | css=tr:nth-child(3) input | 
 
   driver.findElement(By.cssSelector("tr:nth-child(3) input")).click();


    // 21 | click | css=input:nth-child(9) | 
  
  driver.findElement(By.cssSelector("input:nth-child(9)")).click();
 

   // 22 | click | name=passengerFirstName | 
 
   driver.findElement(By.name("passengerFirstName")).click();
  

  // 23 | type | name=passengerFirstName | charles
  
  driver.findElement(By.name("passengerFirstName")).sendKeys("charles");


    // 24 | click | name=passengerLastName | 
   
 driver.findElement(By.name("passengerLastName")).click();


    // 25 | type | name=passengerLastName | chaplin
  
  driver.findElement(By.name("passengerLastName")).sendKeys("chaplin");
 

   // 26 | click | css=input:nth-child(5) | 
 
   driver.findElement(By.cssSelector("input:nth-child(5)")).click();


    // 27 | click | name=card_type | 
  
  driver.findElement(By.name("card_type")).click();


    // 28 | click | name=card_number | 
 
   driver.findElement(By.name("card_number")).click();


    // 29 | type | name=card_number | 1234567800
  
  driver.findElement(By.name("card_number")).sendKeys("1234567800");
 

   // 30 | click | name=expiry_month | 
  
  driver.findElement(By.name("expiry_month")).click();
  

  // 31 | select | name=expiry_month | label=07
  
  {
   
   WebElement dropdown = driver.findElement(By.name("expiry_month"));

      dropdown.findElement(By.xpath("//option[. = '07']")).click();


  }
  

  // 32 | click | name=expiry_year | 
 
   driver.findElement(By.name("expiry_year")).click();


    // 33 | select | name=expiry_year | label=2025
  
  {
  
    WebElement dropdown = driver.findElement(By.name("expiry_year"));
 
     dropdown.findElement(By.xpath("//option[. = '2025']")).click();
  

  }
 

   // 34 | click | css=p > input | 
 
   driver.findElement(By.cssSelector("p > input")).click();
 

   // 35 | click | linkText=Sign off | 
 
   driver.findElement(By.linkText("Sign off")).click();
  

  // 36 | close |  | 
   
 driver.close();

 
 }


}
