// Generated by Selenium IDE

import org.junit.Test;

import org.junit.Before;

import org.junit.After;

import static org.junit.Assert.*;

import static org.hamcrest.CoreMatchers.is;

import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;

import org.openqa.selenium.WebDriver;

import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.remote.RemoteWebDriver;

import org.openqa.selenium.remote.DesiredCapabilities;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.WebElement;

import org.openqa.selenium.interactions.Actions;

import org.openqa.selenium.support.ui.ExpectedConditions;

import org.openqa.selenium.support.ui.WebDriverWait;

import org.openqa.selenium.JavascriptExecutor;

import org.openqa.selenium.Alert;

import org.openqa.selenium.Keys;

import java.util.*;

import java.net.MalformedURLException;

import java.net.URL;


public class Prueba2Test {
 
 private WebDriver driver;

  private Map<String, Object> vars;

  JavascriptExecutor js;


  @Before

  public void setUp() {
 
   driver = new ChromeDriver();

    js = (JavascriptExecutor) driver;

    vars = new HashMap<String, Object>();

  }
 

 @After

  public void tearDown() {

    driver.quit();

  }

 
 @Test

  public void prueba2() {


    // Test name: Prueba 2
 

   // Step # | name | target | value
    // 1 | open | /login | 


    driver.get("http://travel.agileway.net/login");


    // 2 | setWindowSize | 1050x840 | 

    driver.manage().window().setSize(new Dimension(1050, 840));


    // 3 | type | id=username | agileway
  
  driver.findElement(By.id("username")).sendKeys("agileway");
 

   // 4 | click | id=password | 
 
   driver.findElement(By.id("password")).click();


    // 5 | type | id=password | testwise
 
   driver.findElement(By.id("password")).sendKeys("testwise");


    // 6 | click | name=commit |
 
    driver.findElement(By.name("commit")).click();


    // 7 | click | name=fromPort | 

    driver.findElement(By.name("fromPort")).click();


    // 8 | select | name=fromPort | label=Sydney
 
   {
  
    WebElement dropdown = driver.findElement(By.name("fromPort"));

      dropdown.findElement(By.xpath("//option[. = 'Sydney']")).click();

    }
 

   // 9 | click | name=toPort | 
 
   driver.findElement(By.name("toPort")).click();


    // 10 | select | name=toPort | label=New York
 
   {
 
     WebElement dropdown = driver.findElement(By.name("toPort"));

      dropdown.findElement(By.xpath("//option[. = 'New York']")).click();

    }
 

   // 11 | click | id=departDay | 
 
   driver.findElement(By.id("departDay")).click();
  

  // 12 | select | id=departDay | label=04
 
   {

      WebElement dropdown = driver.findElement(By.id("departDay"));

      dropdown.findElement(By.xpath("//option[. = '04']")).click();

    }


    // 13 | click | id=returnDay | 
 
   driver.findElement(By.id("returnDay")).click();
 

   // 14 | select | id=returnDay | label=09
  
  {
  
    WebElement dropdown = driver.findElement(By.id("returnDay"));

      dropdown.findElement(By.xpath("//option[. = '09']")).click();

    }
 

   // 15 | click | id=returnMonth | 

    driver.findElement(By.id("returnMonth")).click();


    // 16 | select | id=returnMonth | label=June 2023
  
  {
  
    WebElement dropdown = driver.findElement(By.id("returnMonth"));

      dropdown.findElement(By.xpath("//option[. = 'June 2023']")).click();

    }
 

   // 17 | click | css=tr:nth-child(2) input | 
 
   driver.findElement(By.cssSelector("tr:nth-child(2) input")).click();


    // 18 | click | css=input:nth-child(9) | 

    driver.findElement(By.cssSelector("input:nth-child(9)")).click();


    // 19 | click | name=passengerFirstName | 

    driver.findElement(By.name("passengerFirstName")).click();


    // 20 | type | name=passengerFirstName | charles
 
   driver.findElement(By.name("passengerFirstName")).sendKeys("charles");


    // 21 | click | name=passengerLastName | 

    driver.findElement(By.name("passengerLastName")).click();


    // 22 | type | name=passengerLastName | chaplin
  
  driver.findElement(By.name("passengerLastName")).sendKeys("chaplin");
 

   // 23 | click | css=input:nth-child(5) | 
 
   driver.findElement(By.cssSelector("input:nth-child(5)")).click();


    // 24 | click | css=td > input:nth-child(2) | 
 
   driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();
 

   // 25 | click | name=card_number | 

    driver.findElement(By.name("card_number")).click();


    // 26 | type | name=card_number | 0000000001
 
   driver.findElement(By.name("card_number")).sendKeys("0000000001");
 

   // 27 | click | name=expiry_month | 
 
   driver.findElement(By.name("expiry_month")).click();


    // 28 | select | name=expiry_month | label=11
 
   {
    
  WebElement dropdown = driver.findElement(By.name("expiry_month"));
 
     dropdown.findElement(By.xpath("//option[. = '11']")).click();

    }
 

   // 29 | click | name=expiry_year | 
  
  driver.findElement(By.name("expiry_year")).click();


    // 30 | select | name=expiry_year | label=2024

    {
 
     WebElement dropdown = driver.findElement(By.name("expiry_year"));

      dropdown.findElement(By.xpath("//option[. = '2024']")).click();

    }
 

   // 31 | click | css=p > input | 
 
   driver.findElement(By.cssSelector("p > input")).click();
 

   // 32 | click | linkText=Sign off | 
 
   driver.findElement(By.linkText("Sign off")).click();
 
 }


}
