// Generated by Selenium IDE

import org.junit.Test;

import org.junit.Before;

import org.junit.After;

import static org.junit.Assert.*;

import static org.hamcrest.CoreMatchers.is;

import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.remote.RemoteWebDriver;

import org.openqa.selenium.remote.DesiredCapabilities;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.WebElement;

import org.openqa.selenium.interactions.Actions;

import org.openqa.selenium.support.ui.ExpectedConditions;

import org.openqa.selenium.support.ui.WebDriverWait;

import org.openqa.selenium.JavascriptExecutor;

import org.openqa.selenium.Alert;

import org.openqa.selenium.Keys;

import java.util.*;

import java.net.MalformedURLException;

import java.net.URL;


public class Prueba1Test {
  
private WebDriver driver;

  private Map<String, Object> vars;

  JavascriptExecutor js;

  
@Before
 
 public void setUp() {
  
  driver = new ChromeDriver();

    js = (JavascriptExecutor) driver;
 
   vars = new HashMap<String, Object>();

  }
 
 @After
 
 public void tearDown() {
 
   driver.quit();
 
 }
 

 @Test

  public void prueba1() {

    // Test name: Prueba 1
 
   // Step # | name | target | value
 
 
  // 1 | open | /login | 

    driver.get("http://travel.agileway.net/login");


    // 2 | setWindowSize | 1050x840 | 

    driver.manage().window().setSize(new Dimension(1050, 840));
  

  // 3 | click | id=username | 
  
  driver.findElement(By.id("username")).click();


    // 4 | type | id=username | agileway
  
  driver.findElement(By.id("username")).sendKeys("agileway");


    // 5 | click | id=password | 
 
   driver.findElement(By.id("password")).click();
 

   // 6 | type | id=password | testwise
 
   driver.findElement(By.id("password")).sendKeys("testwise");
 

   // 7 | click | name=commit | 
  
  driver.findElement(By.name("commit")).click();


    // 8 | click | name=fromPort | 
 
   driver.findElement(By.name("fromPort")).click();


    // 9 | select | name=fromPort | label=New York
 
   {
    
  WebElement dropdown = driver.findElement(By.name("fromPort"));

      dropdown.findElement(By.xpath("//option[. = 'New York']")).click();
 
   }
 

   // 10 | click | name=toPort | 

    driver.findElement(By.name("toPort")).click();
 

   // 11 | select | name=toPort | label=New York
   
 {
   
   WebElement dropdown = driver.findElement(By.name("toPort"));

      dropdown.findElement(By.xpath("//option[. = 'New York']")).click();


    }
  


  // 12 | click | name=toPort | 
 
   driver.findElement(By.name("toPort")).click();
 

   // 13 | select | name=toPort | label=Sydney
   
 {
 
     WebElement dropdown = driver.findElement(By.name("toPort"));
 
     dropdown.findElement(By.xpath("//option[. = 'Sydney']")).click();
 

   }
 

   // 14 | click | id=returnDay | 
 
   driver.findElement(By.id("returnDay")).click();
 

   // 15 | select | id=returnDay | label=18
    
 {
  
    WebElement dropdown = driver.findElement(By.id("returnDay"));
 
     dropdown.findElement(By.xpath("//option[. = '18']")).click();
 
  
 }
  

 // 16 | click | id=returnMonth | 
  
  driver.findElement(By.id("returnMonth")).click();
 

   // 17 | select | id=returnMonth | label=August 2023


   {
   
   WebElement dropdown = driver.findElement(By.id("returnMonth"));
 
     dropdown.findElement(By.xpath("//option[. = 'August 2023']")).click();


    }
 

   // 18 | click | css=tr:nth-child(1) > th > input | 
 
   driver.findElement(By.cssSelector("tr:nth-child(1) > th > input")).click();


    // 19 | click | css=input:nth-child(9) | 
 
   driver.findElement(By.cssSelector("input:nth-child(9)")).click();
 

   // 20 | click | name=passengerFirstName | 
  
  driver.findElement(By.name("passengerFirstName")).click();

    // 21 | type | name=passengerFirstName | charles
 
   driver.findElement(By.name("passengerFirstName")).sendKeys("charles");


    // 22 | click | name=passengerLastName | 
 
   driver.findElement(By.name("passengerLastName")).click();
 

   // 23 | type | name=passengerLastName | chaplin
 
   driver.findElement(By.name("passengerLastName")).sendKeys("chaplin");
  

  // 24 | click | css=input:nth-child(5) | 
   
 driver.findElement(By.cssSelector("input:nth-child(5)")).click();
  

  // 25 | click | name=card_type | 
 
   driver.findElement(By.name("card_type")).click();
 

   // 26 | click | name=card_number | 
 
   driver.findElement(By.name("card_number")).click();
 

   // 27 | type | name=card_number | 12345678920
  
  driver.findElement(By.name("card_number")).sendKeys("12345678920");
 

   // 28 | click | name=expiry_month | 

    driver.findElement(By.name("expiry_month")).click();
  

  // 29 | select | name=expiry_month | label=10
   

 {
   
   WebElement dropdown = driver.findElement(By.name("expiry_month"));
   
   dropdown.findElement(By.xpath("//option[. = '10']")).click();
  

  }
 

   // 30 | click | css=p > input | 
 
   driver.findElement(By.cssSelector("p > input")).click();
 

   // 31 | click | linkText=Sign off | 
 
   driver.findElement(By.linkText("Sign off")).click();
 
 }


}
